-- AlterTable
ALTER TABLE "Fight" ALTER COLUMN "result" SET DATA TYPE TEXT,
ALTER COLUMN "opponent_name" SET DATA TYPE TEXT,
ALTER COLUMN "event" SET DATA TYPE TEXT,
ALTER COLUMN "decision" SET DATA TYPE TEXT;
